module.exports=(sequelize,Sequelize)=>{
    const User=sequelize.define('User',{
        isAdmin:{
            type:Sequelize.BOOLEAN,
            allowNull:false
        },
        salary:{
            type:Sequelize.INTEGER,
            allowNull:false
        },
        email:{
            type:Sequelize.STRING,
            allowNull:false,
            primaryKey:true
        },
        password:{
            type:Sequelize.STRING,
            allowNull:false
        },
        nic:{
            type:Sequelize.STRING,
            allowNull:false,
        },
        fuel:{
            type:Sequelize.INTEGER,
            allowNull:false
        },
        firstName:{
            type:Sequelize.STRING,
            allowNull:false
        },
        lastName:{
            type:Sequelize.STRING,
            allowNull:false
        },
        DOB:{
            type:Sequelize.STRING,
            allowNull:false
        },
        experience:{
            type:Sequelize.STRING,
            allowNull:true
        },
        Department:{
            type:Sequelize.STRING,
            allowNull:false
        },
        designation:{
            type:Sequelize.STRING,
            allowNull:false
        },
        pic_location:{
            type:Sequelize.STRING,
            allowNull:false
        },
        healthInsurance:{
            type:Sequelize.STRING,
            allowNull:false
        },
        benificiaries:{
            type:Sequelize.INTEGER,
            allowNull:false
        }
    
    }
    );
    return User;
    
}

